[meta]
name = "Editor Route"
author = "Wambo"
category = "Map Editor"
version = "0.9.8 Beta"
siteid = 489

[script]
timeout = 0
defines = ["ER_DEBUG"]
dependencies = [ "Camera", "VehicleState" ]
optional_dependencies = [ "Editor" ]